#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server.

if [ $# -lt 3 ]; then
    echo " Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi


file_path="$1"
server_ip="$2"
username="$3"
SSH_path="$4"

if [ $# -lt 4 ]; then
    scp -o StrictHostKeyChecking=no -i "$file_path" "$username"@"$server_ip" :~/
    exit
fi
    scp -o StrictHostKeyChecking=no -i "$SSH_path" "$file_path" "$username"@"$server_ip" :~/
