#!/usr/bin/env bash
#install_nginx_web_server.

sudo su
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start