#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

# Update package list & Installing Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Allowing write permissions to the HTML file & Add content to the HTML file
sudo chmod 666 /var/www/html/index.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

# Adding a location block for /redirect_me in the Nginx configuration
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.linkedin.com\/in\/mohamed-ezzat01;\n\t}' /etc/nginx/sites-available/default

# Starting the Nginx service
sudo service nginx restart
