#!/usr/bin/env bash

# This Bash script automates the process of creating a backup of all databases in a MySQL server
# and compressing it into a tar.gz archive with a filename formatted as day-month-year.tar.gz.

# Check if password argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

# MySQL dump command
mysqldump -u root --password="${1}" --all-databases > backup.sql

# Check if mysqldump was successful
if [ $? -ne 0 ]; then
    echo "MySQL dump failed. Exiting..."
    exit 1
fi

# Compress MySQL dump to tar.gz archive
DATE=$(date +"%d-%m-%Y")
tar -czvf "$DATE.tar.gz" backup.sql

# Check if compression was successful
if [ $? -ne 0 ]; then
    echo "Compression failed. Exiting..."
    exit 1
fi

# Clean up
rm backup.sql

echo "MySQL dump created and compressed successfully as $DATE.tar.gz"

